version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: shilton-elasticsearch
    environment:
      - node.name=shilton-elasticsearch01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdatadir:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: shilton-kibana
    environment:
      SERVER_NAME: 172.30.48.1
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - elastic
      
networks:
  elastic: