version: '2.2'
services:
  shilton-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: shilton-elasticsearch-container
    environment:
      - node.name=shilton-elasticsearch01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdatadir:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

networks:
  elastic: